# Generated by Django 4.0.6 on 2022-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_post1_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='movie_gne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post1',
            name='movie_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
