# Generated by Django 4.0.6 on 2022-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_post1_movie_gne_post1_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='movie_gne',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Western', 'Western'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Music', 'Music')], max_length=200, null=True),
        ),
    ]
